# Generated by Django 5.0.4 on 2024-05-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matrimonio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('novio', models.CharField(max_length=60)),
                ('novia', models.CharField(max_length=60)),
                ('domicilio', models.CharField(max_length=60)),
                ('ciudad_sacramento', models.CharField(max_length=60)),
                ('padres_novio', models.CharField(max_length=60)),
                ('padres_novia', models.CharField(max_length=60)),
                ('testigos', models.CharField(max_length=60)),
                ('presentacion', models.CharField(max_length=60)),
                ('fecha_sacramento', models.DateField()),
                ('presbitero', models.CharField(max_length=60)),
                ('libro', models.IntegerField()),
                ('pagina', models.IntegerField()),
                ('partida', models.IntegerField()),
                ('notas', models.CharField(max_length=60)),
            ],
        ),
    ]
