# Generated by Django 5.0.4 on 2024-05-09 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sacramento', models.DateField(default=django.utils.timezone.now, help_text='Fecha cuando se ejerció el sacramento.')),
                ('presbitero', models.CharField(help_text='Nombre completo del presbítero a cargo.', max_length=100)),
                ('libro', models.PositiveSmallIntegerField(help_text='Representa el número del libro según el sacramento.')),
                ('pagina', models.PositiveSmallIntegerField(help_text='Representa el número de página según el libro.')),
                ('partida', models.PositiveSmallIntegerField(help_text='Representa el número de partida según la página.')),
                ('notas', models.CharField(blank=True, default='N/A', help_text='Cualquier consideración o notas adicionales.', max_length=1000)),
                ('novio', models.CharField(help_text='Nombre completo del novio.', max_length=100)),
                ('novia', models.CharField(help_text='Nombre completo de la novia.', max_length=100)),
                ('domicilio', models.CharField(help_text='Domicilio de los novios, anotado en cualquier formato.', max_length=100)),
                ('ciudad_sacramento', models.CharField(default='Hermosillo, Sonora', help_text='Ciudad donde se recibió el sacramento en custión.', max_length=100)),
                ('padres_novio', models.CharField(help_text='Nombre completo de los padres del novio, separado con espacios y una coma donde sea necesario.', max_length=200)),
                ('padres_novia', models.CharField(help_text='Nombre completo de los padres de la novia, separado con espacios y una coma donde sea necesario.', max_length=200)),
                ('testigos', models.CharField(help_text='Nombre completo de los testigos, separado con espacios y comas donde sea necesario.', max_length=500)),
                ('presentacion', models.CharField(help_text='Presentación matrimonial o anotaciones particulares.', max_length=100)),
            ],
            options={
                'ordering': ['-fecha_sacramento', 'novio', 'novia'],
            },
        ),
    ]
