# Generated by Django 5.0.4 on 2024-05-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
