# Generated by Django 5.0.4 on 2024-05-08 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirmacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmacion',
            name='fecha_sacramento',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 7, 5, 55, 998610, tzinfo=datetime.timezone.utc), help_text='Fecha cuando se ejerció el sacramento.'),
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='libro',
            field=models.PositiveSmallIntegerField(help_text='Representa el número del libro según el sacramento.'),
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='pagina',
            field=models.PositiveSmallIntegerField(help_text='Representa el número de página según el libro.'),
        ),
        migrations.AlterField(
            model_name='confirmacion',
            name='partida',
            field=models.PositiveSmallIntegerField(help_text='Representa el número de partida según la página.'),
        ),
    ]
