# Generated by Django 5.0.4 on 2024-05-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('sexo', models.BooleanField(default=False)),
                ('padre', models.CharField(max_length=255)),
                ('madre', models.CharField(max_length=255)),
                ('padrino_madrina', models.CharField(max_length=255)),
                ('ciudad_bautizo', models.CharField(default='Hermosillo, Sonora', max_length=255)),
                ('parroquia_bautizo', models.CharField(max_length=255)),
                ('fecha_bautizo', models.DateField()),
            ],
        ),
    ]
