# Generated by Django 5.0.4 on 2024-05-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('read', 'Solo lectura'), ('write', 'Lectura y Escritura'), ('admin', 'Administrador')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
