# Generated by Django 5.0.4 on 2024-05-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('admin', 'Administrador'), ('write', 'Lectura y Escritura'), ('read', 'Solo lectura')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
